To jest pierwszy notebook w temacie: <span style="color:red;font-size:16pt;font-weight:bold;">biblioteka Pandas</span>
<p><img src="supernova.jpg" width=300></p>

In [1]:
import numpy as np

In [2]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [3]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [6]:
zlista = [4,7,5,8,64,25,6,8,5,78,5545,6]
print(zlista)
print(type(zlista))

[4, 7, 5, 8, 64, 25, 6, 8, 5, 78, 5545, 6]
<class 'list'>


In [7]:
k=np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [8]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[   4    7    5    8   64   25    6    8    5   78 5545    6]
<class 'numpy.ndarray'>


In [9]:
kl = (4,323,5,2,787,64,3)
knum = np.array(kl)
print(knum)
print(type(knum))

[  4 323   5   2 787  64   3]
<class 'numpy.ndarray'>


In [10]:
zl = {56,3,4,58,90,21,38,36,8,3,3}
znum = np.array(zl)
print(znum)
print(type(znum))

{3, 4, 90, 38, 36, 8, 21, 56, 58}
<class 'numpy.ndarray'>


In [11]:
knum.sort()
print(knum)

[  2   3   4   5  64 323 787]


In [12]:
# znum.sort()
# print(znum)

In [13]:
l1 = [2,4,6,9]
l2 = [5,6,78,9,13]
l3 = [112,89,12]

l1 = l1+l2+l3

l1

[2, 4, 6, 9, 5, 6, 78, 9, 13, 112, 89, 12]

In [14]:
a = np.array(l1)
b = np.array(l2)
c = np.array(l3)

In [15]:
# a = a+b+c
a  = np.concatenate((a,b,c))
a

array([ 2, 4, 6, 9, 5, 6, 78, 9, 13, 112, 89, 12, 5,
 6, 78, 9, 13, 112, 89, 12])

In [16]:
z1 = [[56,2],[64,2]]
z1

[[56, 2], [64, 2]]

In [17]:
a1 = np.array([[2,9],[7,15]])
a1

array([[ 2, 9],
 [ 7, 15]])

In [18]:
z1[0][1]

2

In [19]:
a1[0][1]

9

In [20]:
a1[0,1]

9

In [21]:
x = np.array([[3,4],[6,8]])
y = np.array([[7,11],[19,3]])

p = np.concatenate((x,y),axis=1)
p

array([[ 3, 4, 7, 11],
 [ 6, 8, 19, 3]])

In [22]:
prosta = np.arange(12)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [23]:
fp = prosta.reshape(3,4)
fp

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])

In [24]:
mac1 = np.array([[2,3],[4,5],[9,9]])

mac1

array([[2, 3],
 [4, 5],
 [9, 9]])

In [25]:
mac1.shape

(3, 2)

In [26]:
w1 = mac1.reshape(6)
w1

array([2, 3, 4, 5, 9, 9])

In [27]:
ar = np.array([1,6,78,9,1,4,21,24,12,1,1,3,-3])
ar.shape

(13,)

In [28]:
ar[:7]

array([ 1, 6, 78, 9, 1, 4, 21])

In [29]:
ar[2:5]

array([78, 9, 1])

In [30]:
w = np.array([[1,2,3,4],[9,10,11,12],[35,36,21,99]])
w

array([[ 1, 2, 3, 4],
 [ 9, 10, 11, 12],
 [35, 36, 21, 99]])

In [31]:
w[w<5]

array([1, 2, 3, 4])

In [32]:
pc = (w>5)
w[pc]

array([ 9, 10, 11, 12, 35, 36, 21, 99])

In [33]:
pv = (w%2==0)
w[pv]

array([ 2, 4, 10, 12, 36])

In [34]:
cv = w[(w>2)&(w<21)]
cv

array([ 3, 4, 9, 10, 11, 12])

In [35]:
sv = w[(w<8)|(w>50)]
sv

array([ 1, 2, 3, 4, 99])

In [36]:
#operacje arytmetyczne na wektorach (macierzach)
dane = np.array([1,3,8])
ones = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [37]:
print(dane+ones)

[2 4 9]


In [38]:
print(dane-ones)

[0 2 7]


In [39]:
print(dane*tw)

[ 2  6 24]


In [40]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [41]:
print(dane*1.88)

[ 1.88  5.64 15.04]


In [42]:
inny = np.array([3,3,2,2])

In [48]:
# print(dane + inny)
#szybki komentarz CTRL + /
# print(np.dot(dane,inny))

In [49]:
m1 = np.array([[4,8,11],[67,101,3],[1,1,77]])
m2 = np.array([[78,5,4],[11,12,55],[0,6,12]])
wynik = (m1+m2)*m1
wynik

array([[ 328, 104, 165],
 [ 5226, 11413, 174],
 [ 1, 7, 6853]])

In [50]:
print(f'wartość najmniejsza: {wynik.min()}')
print(f'wartość największa: {wynik.max()}')
print(f'wartość średnia: {wynik.mean()}')

wartość najmniejsza: 1
wartość największa: 11413
wartość średnia: 2696.777777777778
