To jest pierwszy notebook w temacie: <span style="color:red;font-size:16pt;font-weight:bold;">biblioteka Pandas</span>
<p><img src="supernova.jpg" width=300></p>

In [1]:
import numpy as np

In [2]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [3]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [6]:
zlista = [4,7,5,8,64,25,6,8,5,78,5545,6]
print(zlista)
print(type(zlista))

[4, 7, 5, 8, 64, 25, 6, 8, 5, 78, 5545, 6]
<class 'list'>


In [7]:
k=np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [8]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[   4    7    5    8   64   25    6    8    5   78 5545    6]
<class 'numpy.ndarray'>


In [9]:
kl = (4,323,5,2,787,64,3)
knum = np.array(kl)
print(knum)
print(type(knum))

[  4 323   5   2 787  64   3]
<class 'numpy.ndarray'>


In [10]:
zl = {56,3,4,58,90,21,38,36,8,3,3}
znum = np.array(zl)
print(znum)
print(type(znum))

{3, 4, 90, 38, 36, 8, 21, 56, 58}
<class 'numpy.ndarray'>


In [11]:
knum.sort()
print(knum)

[  2   3   4   5  64 323 787]


In [13]:
# znum.sort()
# print(znum)

In [14]:
l1 = [2,4,6,9]
l2 = [5,6,78,9,13]
l3 = [112,89,12]

l1 = l1+l2+l3

l1

[2, 4, 6, 9, 5, 6, 78, 9, 13, 112, 89, 12]

In [15]:
a = np.array(l1)
b = np.array(l2)
c = np.array(l3)

In [17]:
# a = a+b+c
a  = np.concatenate((a,b,c))
a

array([ 2, 4, 6, 9, 5, 6, 78, 9, 13, 112, 89, 12, 5,
 6, 78, 9, 13, 112, 89, 12])