In [1]:
import numpy as np

In [2]:
#Transponowanie tablic i zmiana osi

arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [4]:
arr = np.random.randn(6,3)
arr

array([[-0.97713382, -1.27550271, -0.67877987],
 [-0.89967016, 0.43464387, 0.90607699],
 [ 0.47148627, 0.08720769, 0.79988347],
 [ 1.39898943, 1.10855628, -0.71327302],
 [ 0.54510522, 0.0279533 , -0.41677429],
 [-0.29783697, 0.53288208, -0.51437071]])

In [5]:
arr.T

array([[-0.97713382, -0.89967016, 0.47148627, 1.39898943, 0.54510522,
 -0.29783697],
 [-1.27550271, 0.43464387, 0.08720769, 1.10855628, 0.0279533 ,
 0.53288208],
 [-0.67877987, 0.90607699, 0.79988347, -0.71327302, -0.41677429,
 -0.51437071]])

In [6]:
np.dot(arr.T,arr)

array([[ 4.32951417, 2.30380196, -0.84662622],
 [ 2.30380196, 3.33706938, 0.25290993],
 [-0.84662622, 0.25290993, 2.86856763]])

In [7]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [10]:
arr = np.arange(240).reshape((2,2,4,5,3))
arr

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1