In [2]:
#Struktury danych biblioteki PANDAS
#Obiekt Series

import pandas as pd

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0 4
1 7
2 -5
3 3
dtype: int64

In [4]:
obj.values

array([ 4, 7, -5, 3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3], index=['a','b','d','c'])
obj2

a 4
b 7
d -5
c 3
dtype: int64

In [7]:
obj2.index

Index(['a', 'b', 'd', 'c'], dtype='object')

In [8]:
obj2['a']

4

In [9]:
obj2['d'] = 455
obj2

a 4
b 7
d 455
c 3
dtype: int64

In [10]:
obj2[['c','a','d']]

c 3
a 4
d 455
dtype: int64

In [11]:
obj2[obj2>6]

b 7
d 455
dtype: int64

In [12]:
obj2*2

a 8
b 14
d 910
c 6
dtype: int64

In [13]:
'b' in obj2

True

In [14]:
'z' in obj2

False

In [15]:
sdata = {'Warszawa':45678,'Kraków':43256,"Lublin":38900,"Gdańsk":40876}
sdata

{'Warszawa': 45678, 'Kraków': 43256, 'Lublin': 38900, 'Gdańsk': 40876}

In [16]:
obj3 = pd.Series(sdata)
obj3

Warszawa 45678
Kraków 43256
Lublin 38900
Gdańsk 40876
dtype: int64

In [17]:
miasta = ['Poznań','Kraków','Rzeszów','Lublin']
obj4 = pd.Series(sdata,index=miasta)
obj4

Poznań NaN
Kraków 43256.0
Rzeszów NaN
Lublin 38900.0
dtype: float64

In [18]:
pd.isnull(obj4)

Poznań True
Kraków False
Rzeszów True
Lublin False
dtype: bool

In [19]:
obj3+obj4

Gdańsk NaN
Kraków 86512.0
Lublin 77800.0
Poznań NaN
Rzeszów NaN
Warszawa NaN
dtype: float64

In [20]:
#obiekt DataFrame

data = {'miasto':['Warszawa','Warszawa','Warszawa',"Kraków","Kraków","Kraków"],
        'rok':[2017,2018,2019,2018,2019,2020],
        'populacja': [2.7,2.75,3.05,0.85,0.91,1.05]}

frame = pd.DataFrame(data)

In [21]:
frame

miasto 
 rok 
 populacja 
 
 
 
 
 0 
 Warszawa 
 2017 
 2.70 
 
 
 1 
 Warszawa 
 2018 
 2.75 
 
 
 2 
 Warszawa 
 2019 
 3.05 
 
 
 3 
 Kraków 
 2018 
 0.85 
 
 
 4 
 Kraków 
 2019 
 0.91 
 
 
 5 
 Kraków 
 2020 
 1.05

In [22]:
frame2 = pd.DataFrame(data,columns=['rok','miasto','populacja','waga'],index=['jeden','dwa','trzy',"cztery","pięć","sześć"])
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 NaN 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 NaN 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 NaN 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 NaN 
 
 
 pięć 
 2019 
 Kraków 
 0.91 
 NaN 
 
 
 sześć 
 2020 
 Kraków 
 1.05 
 NaN

In [23]:
frame2['waga'] = 19.99
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 19.99 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 19.99 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 19.99 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 19.99 
 
 
 pięć 
 2019 
 Kraków 
 0.91 
 19.99 
 
 
 sześć 
 2020 
 Kraków 
 1.05 
 19.99

In [24]:
import numpy as np

In [25]:
# frame2['waga'] = np.arange(6.)
frame2['waga'] = np.array([15,17,1.1,45,2,0.1])
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 15.0 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 17.0 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 1.1 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 45.0 
 
 
 pięć 
 2019 
 Kraków 
 0.91 
 2.0 
 
 
 sześć 
 2020 
 Kraków 
 1.05 
 0.1

In [26]:
daty = pd.date_range("20231207",periods=6)
daty

DatetimeIndex(['2023-12-07', '2023-12-08', '2023-12-09', '2023-12-10',
               '2023-12-11', '2023-12-12'],
              dtype='datetime64[ns]', freq='D')

In [27]:
fr = pd.DataFrame(np.random.randn(6,4),index=daty,columns=list("ABCD"))
fr

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-07 
 -0.047379 
 0.245352 
 -0.592430 
 -0.222437 
 
 
 2023-12-08 
 1.599313 
 2.289011 
 1.873700 
 -0.667910 
 
 
 2023-12-09 
 1.008242 
 0.477410 
 -0.752347 
 -0.398430 
 
 
 2023-12-10 
 1.886177 
 0.542365 
 0.846959 
 -1.653105 
 
 
 2023-12-11 
 -1.730968 
 -0.179199 
 0.030732 
 0.597880 
 
 
 2023-12-12 
 0.283727 
 0.459982 
 -0.499937 
 -1.997999

In [28]:
fr.head(3)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-07 
 -0.047379 
 0.245352 
 -0.592430 
 -0.222437 
 
 
 2023-12-08 
 1.599313 
 2.289011 
 1.873700 
 -0.667910 
 
 
 2023-12-09 
 1.008242 
 0.477410 
 -0.752347 
 -0.398430

In [29]:
fr.tail(2)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-11 
 -1.730968 
 -0.179199 
 0.030732 
 0.597880 
 
 
 2023-12-12 
 0.283727 
 0.459982 
 -0.499937 
 -1.997999

In [30]:
fr.to_numpy()

array([[-0.04737941, 0.24535184, -0.59242957, -0.22243741],
 [ 1.59931333, 2.28901091, 1.87370022, -0.66790984],
 [ 1.00824247, 0.47740975, -0.75234708, -0.39843047],
 [ 1.88617701, 0.54236512, 0.84695908, -1.65310515],
 [-1.73096817, -0.17919938, 0.03073158, 0.59788018],
 [ 0.2837273 , 0.45998171, -0.49993728, -1.99799897]])

In [31]:
fr.describe()

A 
 B 
 C 
 D 
 
 
 
 
 count 
 6.000000 
 6.000000 
 6.000000 
 6.000000 
 
 
 mean 
 0.499852 
 0.639153 
 0.151113 
 -0.723667 
 
 
 std 
 1.319993 
 0.850228 
 1.025569 
 0.958581 
 
 
 min 
 -1.730968 
 -0.179199 
 -0.752347 
 -1.997999 
 
 
 25% 
 0.035397 
 0.299009 
 -0.569306 
 -1.406806 
 
 
 50% 
 0.645985 
 0.468696 
 -0.234603 
 -0.533170 
 
 
 75% 
 1.451546 
 0.526126 
 0.642902 
 -0.266436 
 
 
 max 
 1.886177 
 2.289011 
 1.873700 
 0.597880

In [32]:
fr.T

2023-12-07 
 2023-12-08 
 2023-12-09 
 2023-12-10 
 2023-12-11 
 2023-12-12 
 
 
 
 
 A 
 -0.047379 
 1.599313 
 1.008242 
 1.886177 
 -1.730968 
 0.283727 
 
 
 B 
 0.245352 
 2.289011 
 0.477410 
 0.542365 
 -0.179199 
 0.459982 
 
 
 C 
 -0.592430 
 1.873700 
 -0.752347 
 0.846959 
 0.030732 
 -0.499937 
 
 
 D 
 -0.222437 
 -0.667910 
 -0.398430 
 -1.653105 
 0.597880 
 -1.997999

In [34]:
fr.sort_index(axis=0,ascending=False)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-12 
 0.283727 
 0.459982 
 -0.499937 
 -1.997999 
 
 
 2023-12-11 
 -1.730968 
 -0.179199 
 0.030732 
 0.597880 
 
 
 2023-12-10 
 1.886177 
 0.542365 
 0.846959 
 -1.653105 
 
 
 2023-12-09 
 1.008242 
 0.477410 
 -0.752347 
 -0.398430 
 
 
 2023-12-08 
 1.599313 
 2.289011 
 1.873700 
 -0.667910 
 
 
 2023-12-07 
 -0.047379 
 0.245352 
 -0.592430 
 -0.222437

In [36]:
fr.sort_values(by="B",ascending=False)

A 
 B 
 C 
 D 
 
 
 
 
 2023-12-08 
 1.599313 
 2.289011 
 1.873700 
 -0.667910 
 
 
 2023-12-10 
 1.886177 
 0.542365 
 0.846959 
 -1.653105 
 
 
 2023-12-09 
 1.008242 
 0.477410 
 -0.752347 
 -0.398430 
 
 
 2023-12-12 
 0.283727 
 0.459982 
 -0.499937 
 -1.997999 
 
 
 2023-12-07 
 -0.047379 
 0.245352 
 -0.592430 
 -0.222437 
 
 
 2023-12-11 
 -1.730968 
 -0.179199 
 0.030732 
 0.597880

In [37]:
obj5 = pd.Series([4.5,7.2,-5.6,5],index=['d','a','k','h'])
obj5

d 4.5
a 7.2
k -5.6
h 5.0
dtype: float64

In [42]:
obj6 = obj5.reindex(['d','k','a','h','q'])
obj6

d 4.5
k -5.6
a 7.2
h 5.0
q NaN
dtype: float64

In [43]:
obj7 = pd.Series(['blue','yellow','purple','white'],index=[0,2,5,8])
obj7

0 blue
2 yellow
5 purple
8 white
dtype: object

In [44]:
obj7.reindex(range(10),method="ffill")

0 blue
1 blue
2 yellow
3 yellow
4 yellow
5 purple
6 purple
7 purple
8 white
9 white
dtype: object

In [46]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Kraków','Warszawa','Lublin','Katowice'],
                    columns=['cecha_1','cecha_2','cecha_3','cecha_4'])
data

cecha_1 
 cecha_2 
 cecha_3 
 cecha_4 
 
 
 
 
 Kraków 
 0 
 1 
 2 
 3 
 
 
 Warszawa 
 4 
 5 
 6 
 7 
 
 
 Lublin 
 8 
 9 
 10 
 11 
 
 
 Katowice 
 12 
 13 
 14 
 15

In [47]:
data['cecha_2']

Kraków 1
Warszawa 5
Lublin 9
Katowice 13
Name: cecha_2, dtype: int64

In [49]:
data.loc['Kraków',['cecha_1','cecha_4']]

cecha_1 0
cecha_4 3
Name: Kraków, dtype: int64

In [50]:
data.iloc[2,[3,0,1]]

cecha_4 11
cecha_1 8
cecha_2 9
Name: Lublin, dtype: int64

In [51]:
data.iloc[[1,2],[3,1,0]]

cecha_4 
 cecha_2 
 cecha_1 
 
 
 
 
 Warszawa 
 7 
 5 
 4 
 
 
 Lublin 
 11 
 9 
 8

In [52]:
data.loc[:"Lublin","cecha_4"]

Kraków 3
Warszawa 7
Lublin 11
Name: cecha_4, dtype: int64

In [57]:
data.iloc[:,:3][data.cecha_3>10]

cecha_1 
 cecha_2 
 cecha_3 
 
 
 
 
 Katowice 
 12 
 13 
 14

In [58]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                   index=['Kraków','Gdańsk','Toruń'])
df1

b 
 c 
 d 
 
 
 
 
 Kraków 
 0.0 
 1.0 
 2.0 
 
 
 Gdańsk 
 3.0 
 4.0 
 5.0 
 
 
 Toruń 
 6.0 
 7.0 
 8.0

In [59]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                   index=['Lublin','Kraków','Gdańsk','Rzeszów'])
df2

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 1.0 
 2.0 
 
 
 Kraków 
 3.0 
 4.0 
 5.0 
 
 
 Gdańsk 
 6.0 
 7.0 
 8.0 
 
 
 Rzeszów 
 9.0 
 10.0 
 11.0

In [60]:
df1+df2

b 
 c 
 d 
 e 
 
 
 
 
 Gdańsk 
 9.0 
 NaN 
 12.0 
 NaN 
 
 
 Kraków 
 3.0 
 NaN 
 6.0 
 NaN 
 
 
 Lublin 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Rzeszów 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Toruń 
 NaN 
 NaN 
 NaN 
 NaN

In [61]:
df1-df2

b 
 c 
 d 
 e 
 
 
 
 
 Gdańsk 
 -3.0 
 NaN 
 -2.0 
 NaN 
 
 
 Kraków 
 -3.0 
 NaN 
 -2.0 
 NaN 
 
 
 Lublin 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Rzeszów 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Toruń 
 NaN 
 NaN 
 NaN 
 NaN

In [62]:
#zależności pomiędzy obiektami Series i DataFrame

arr = np.arange(12.).reshape((3,4))
arr

array([[ 0., 1., 2., 3.],
 [ 4., 5., 6., 7.],
 [ 8., 9., 10., 11.]])

In [63]:
arr[0]

array([0., 1., 2., 3.])

In [64]:
arr-arr[0]

array([[0., 0., 0., 0.],
 [4., 4., 4., 4.],
 [8., 8., 8., 8.]])

In [65]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Lublin','Kraków',"Gdańsk","Wrocław"])
series = frame.iloc[0]
frame

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 1.0 
 2.0 
 
 
 Kraków 
 3.0 
 4.0 
 5.0 
 
 
 Gdańsk 
 6.0 
 7.0 
 8.0 
 
 
 Wrocław 
 9.0 
 10.0 
 11.0

In [68]:
print(type(frame))
print(type(series))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [66]:
series

b 0.0
d 1.0
e 2.0
Name: Lublin, dtype: float64

In [67]:
frame - series

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 0.0 
 0.0 
 
 
 Kraków 
 3.0 
 3.0 
 3.0 
 
 
 Gdańsk 
 6.0 
 6.0 
 6.0 
 
 
 Wrocław 
 9.0 
 9.0 
 9.0

In [69]:
series2 = pd.Series(range(3),index=['b','e','f'])
frame + series2

b 
 d 
 e 
 f 
 
 
 
 
 Lublin 
 0.0 
 NaN 
 3.0 
 NaN 
 
 
 Kraków 
 3.0 
 NaN 
 6.0 
 NaN 
 
 
 Gdańsk 
 6.0 
 NaN 
 9.0 
 NaN 
 
 
 Wrocław 
 9.0 
 NaN 
 12.0 
 NaN

In [70]:
#funkcje apply oraz map

frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                     index=['Lublin','Kraków','Gdańsk','Wrocław'])
frame

b 
 d 
 e 
 
 
 
 
 Lublin 
 -1.425485 
 -0.367652 
 0.735597 
 
 
 Kraków 
 1.357583 
 0.386168 
 1.902138 
 
 
 Gdańsk 
 0.104239 
 -1.269343 
 0.285333 
 
 
 Wrocław 
 -2.126538 
 -0.762538 
 -0.923089

In [71]:
np.abs(frame)

b 
 d 
 e 
 
 
 
 
 Lublin 
 1.425485 
 0.367652 
 0.735597 
 
 
 Kraków 
 1.357583 
 0.386168 
 1.902138 
 
 
 Gdańsk 
 0.104239 
 1.269343 
 0.285333 
 
 
 Wrocław 
 2.126538 
 0.762538 
 0.923089

In [72]:
f = lambda x:x.max()-x.min()
frame.apply(f)

b 3.484121
d 1.655511
e 2.825226
dtype: float64

In [73]:
frame.apply(f,axis="columns")

Lublin 2.161082
Kraków 1.515969
Gdańsk 1.554676
Wrocław 1.364000
dtype: float64

In [75]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f,axis="columns")

min 
 max 
 
 
 
 
 Lublin 
 -1.425485 
 0.735597 
 
 
 Kraków 
 0.386168 
 1.902138 
 
 
 Gdańsk 
 -1.269343 
 0.285333 
 
 
 Wrocław 
 -2.126538 
 -0.762538

In [76]:
format = lambda x:'%.2f'% x
frame.applymap(format)

b 
 d 
 e 
 
 
 
 
 Lublin 
 -1.43 
 -0.37 
 0.74 
 
 
 Kraków 
 1.36 
 0.39 
 1.90 
 
 
 Gdańsk 
 0.10 
 -1.27 
 0.29 
 
 
 Wrocław 
 -2.13 
 -0.76 
 -0.92

In [77]:
frame['e'].map(format)

Lublin 0.74
Kraków 1.90
Gdańsk 0.29
Wrocław -0.92
Name: e, dtype: object