In [1]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
%matplotlib inline
plt.rc('figure',figsize=(10,6))
np.set_printoptions(precision=4,suppress=True)

In [2]:
#Dane Kategoryczne
values = pd.Series(['apple','orange','apple','apple']*2)
values

0 apple
1 orange
2 apple
3 apple
4 apple
5 orange
6 apple
7 apple
dtype: object

In [3]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [4]:
pd.value_counts(values)

apple 6
orange 2
dtype: int64

In [5]:
values = pd.Series([0,1,0,0]*2)
dim = pd.Series(['apple','orange'])
values

0 0
1 1
2 0
3 0
4 0
5 1
6 0
7 0
dtype: int64

In [6]:
dim

0 apple
1 orange
dtype: object

In [7]:
dim.take(values)

0 apple
1 orange
0 apple
0 apple
0 apple
1 orange
0 apple
0 apple
dtype: object

In [9]:
#typ categorical w bibliotece pandas
fruits = ['apple','orange','apple','apple']*2
N = len(fruits)
df = pd.DataFrame({
    'fruit':fruits,
    'basket_id':np.arange(N),
    'count':np.random.randint(3,15,size=N),
    'weight':np.random.uniform(0,4,size=N)
},
                  columns=['basket_id','fruit','count','weight'])

df

basket_id 
 fruit 
 count 
 weight 
 
 
 
 
 0 
 0 
 apple 
 9 
 0.201952 
 
 
 1 
 1 
 orange 
 10 
 3.224939 
 
 
 2 
 2 
 apple 
 14 
 3.723263 
 
 
 3 
 3 
 apple 
 10 
 1.456118 
 
 
 4 
 4 
 apple 
 10 
 2.763792 
 
 
 5 
 5 
 orange 
 11 
 0.517258 
 
 
 6 
 6 
 apple 
 10 
 3.330746 
 
 
 7 
 7 
 apple 
 4 
 1.273415

In [10]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0 apple
1 orange
2 apple
3 apple
4 apple
5 orange
6 apple
7 apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [12]:
c = fruit_cat.values
type(c)

pandas.core.arrays.categorical.Categorical

In [13]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [14]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [15]:
df['fruit'] = df['fruit'].astype('category')
df.fruit

0 apple
1 orange
2 apple
3 apple
4 apple
5 orange
6 apple
7 apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [16]:
#obliczenia na obiektach typu categorical

np.random.seed(12345)
draws = np.random.randn(1000)

draws[:5]

array([-0.2047, 0.4789, -0.5194, -0.5557, 1.9658])

In [17]:
bins = pd.qcut(draws,4)
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [18]:
bins = pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

['Q2', 'Q3', 'Q2', 'Q2', 'Q4', ..., 'Q3', 'Q2', 'Q1', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [19]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [20]:
bins = pd.Series(bins,name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count','min','max'])
           .reset_index())
results

quartile 
 count 
 min 
 max 
 
 
 
 
 0 
 Q1 
 250 
 -2.949343 
 -0.685484 
 
 
 1 
 Q2 
 250 
 -0.683066 
 -0.010115 
 
 
 2 
 Q3 
 250 
 -0.010032 
 0.628894 
 
 
 3 
 Q4 
 250 
 0.634238 
 3.927528

In [21]:
results['quartile']

0 Q1
1 Q2
2 Q3
3 Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' %lt; 'Q2' %lt; 'Q3' %lt; 'Q4']

In [22]:
#obiekty kategoryczne a zwiększanie wydajności
N = 10_000_000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['go','stop','start','end']*(N//4))

In [23]:
categories = labels.astype('category')

In [24]:
labels.memory_usage()

80000128

In [25]:
categories.memory_usage()

10000332

In [26]:
%time _=labels.astype('category')

CPU times: user 481 ms, sys: 158 ms, total: 638 ms
Wall time: 636 ms
